name = "Irfan Sofyana Putra"
description = "a software engineer, tech enthusiast, and a hobbyist"
keywords = "irfan sofyana putra, software engineering, technology"
image = "irfan_3.png"
theme = "dark"
primary_color = "#4F46E5"
text_align = "center"
gtag_id = "G-FHHLDPRJ98"
base_url = "https://irfansp.dev"
copyright_year = "2024"

[[sections]]
title = "Knowledge Hub"
description = "A growing collection of my thoughts, notes, and discoveries"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Digital Garden"
url = "https://brain.irfansp.dev"

[[sections]]
title = "TIL"
description = "Things I have learned"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "My TILs"
url = "https://til.irfansp.dev"

[[sections]]
title = "Professional Journey"
description = "Discover my work history, projects, and achievements"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Portfolio & Experience"
url = "https://resume.irfansp.dev"

[[sections]]
title = "Connect With Me"
description = "Let's Connect and Collaborate!"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Email"
url = "mailto:mail@irfansp.dev"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/irfansofyana/"
[[sections.items]]
title = "Github"
url = "https://github.com/irfansofyana"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/irfansofyana/"
[[sections.items]]
title = "Facebook"
url = "https://www.facebook.com/irfan.sofyanaputra/"
