name = "Irfan Sofyana Putra"
description = "a software engineer, tech enthusiast, and a hobbyist"
keywords = "irfan sofyana putra, software engineering, technology"
image = "irfan_3.png"
theme = "dark"
primary_color = "#2B3A67"
text_align = "center"
gtag_id = ""
base_url = "https://irfansp.dev"

[[sections]]
title = "My Second Brain"
description = "Thoughts and insights"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Digital Garden"
url = "https://brain.irfansp.dev"

[[sections]]
title = "Career Journey"
description = "Exploring my journey"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Portfolio & Experience"
url = "https://resume.irfansp.dev"

[[sections]]
title = "Let's Connect"
description = "Find me across these platforms"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Email"
url = "mailto:irfansofyana0305@gmail.com"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/irfansofyana/"
[[sections.items]]
title = "Github"
url = "https://github.com/irfansofyana"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/irfansofyana/"
[[sections.items]]
title = "Facebook"
url = "https://www.facebook.com/irfan.sofyanaputra/"
